export enum Color {
  Primary = "var(--primary)",
  Primary_light = "var(--primary_light)",
  Secondary = "var(--secondary)",
  Background_primary = "var(--background_primary)",
  Background_primary_dark = "var(--background_primary_dark)",
  Graphite = "var(--background_graphite)",
  Error = "var(--error)",
  Light = "var(--light)",
  Text_primary = "var(--text_primary)",
  White = "white",
  Green = "#00A340",
  Yellow = "#F3A608",
  Orange = "#F45D2D",
}
